version : '2'
services :
  php:
    container_name: php53-fpm
    build: ./build/php 
    working_dir: "/var/www"
    volumes:
        - ./www/:/var/www
    expose:
      - "9000"

  mysql:
    container_name: mysql
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: rootdocker
    volumes:
        - ./db/:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
    ports:
      - 3306:3306
      
  apache:
    container_name: apache
    build: './build/apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/html
      - ./conf/:/usr/local/apache2/conf
      - ./logs/:/var/log/

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
        PMA_HOST : mysql
    ports:
      - "8000:80"

    ports:
      - "8000:80"
version : '2'
2
services :
3
  php:
4
    container_name: php53-fpm
5
    build: ./build/php 
6
    working_dir: "/var/www"
7
    volumes:
8
        - ./www/:/var/www
9
    expose:
10
      - "9000"
11
​
12
  mysql:
13
    container_name: mysql
14
    image: mysql:5.6
15
    environment:
16
        MYSQL_ROOT_PASSWORD: rootdocker
17
    volumes:
18
        - ./db/:/var/lib/mysql
19
    ports:
20
      - 3306:3306
21
      
22
  apache:
23
    container_name: apache
24
    build: './build/apache/'
25
    depends_on:
26
      - php
27
      - mysql
28
    ports:
29
      - "80:80"
30
    volumes:
31
      - ./www/:/var/www/html
32
      - ./conf/:/usr/local/apache2/conf
33
      - ./logs/:/var/log/
34
​
35
  pma:
36
    image: phpmyadmin/phpmyadmin
37
    container_name: phpmyadmin
38
    restart: always
39
    environment:
40
        PMA_HOST : mysql
